# Generated by Django 5.1.5 on 2025-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupInstances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('profile_pic_url', models.CharField(max_length=1000, null=True)),
                ('profile_url', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
