# Generated by Django 5.1.5 on 2025-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupinstances',
            name='status',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
