# Generated by Django 5.1.4 on 2025-01-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_field', models.CharField(max_length=100)),
                ('password_field', models.CharField(max_length=16)),
            ],
        ),
    ]
