# Generated by Django 5.1.4 on 2025-01-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
