# Generated by Django 5.1.4 on 2025-01-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0002_delete_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=17)),
            ],
        ),
    ]
