# Generated by Django 5.1.4 on 2025-01-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetInstance',
            new_name='TargetInstances',
        ),
    ]
