# Generated by Django 5.1.5 on 2025-02-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_rename_targetinstance_targetinstances'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst_mac', models.CharField(max_length=17)),
                ('src_ip', models.CharField(max_length=40)),
                ('dst_ip', models.CharField(max_length=40)),
                ('packet_data', models.BinaryField(max_length=1024)),
                ('corresponding_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.targetinstances')),
            ],
        ),
    ]
